/**
 * Súbor: src/screens/mapScreen/uiStyles.ts
 * Abstrakt: Definuje pomocné štýly a farebné hodnoty používané editorom mapy.
 */
import { StyleSheet } from "react-native";

export const ui = StyleSheet.create({
  topOverlay: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    gap: 10,
    alignItems: "flex-start",
    zIndex: 60,
    elevation: 60,
  },
  topOverlayLandscape: {
    top: 8,
    left: 8,
    right: 8,
  },
  topRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  topRowLandscape: {
    maxWidth: 340,
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 8,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  topActionsLandscape: {
    alignSelf: "auto",
    flexWrap: "wrap",
    gap: 8,
    maxWidth: 300,
  },
  actionButton: {
    minWidth: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 6,
  },
  actionButtonLandscape: {
    minWidth: 40,
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 11,
  },
  searchPanel: {
    flex: 1,
  },
  searchPanelLandscape: {
    flexBasis: "100%",
    maxWidth: 250,
  },
  searchInput: {
    height: 44,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    color: "#0f172a",
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  searchInputDark: {
    backgroundColor: "#111827",
    borderColor: "#334155",
    color: "#f8fafc",
  },
  searchResults: {
    width: "100%",
    maxWidth: 320,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },
  searchResultsDark: {
    backgroundColor: "#111827",
    borderColor: "#334155",
  },
  searchResultsLandscape: {
    maxWidth: 320,
  },
  searchResultItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    backgroundColor: "#ffffff",
  },
  searchResultItemDark: {
    borderBottomColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#111827",
  },
  searchResultTitle: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "800",
  },
  searchResultTitleDark: {
    color: "#f8fafc",
  },
  searchResultMeta: {
    marginTop: 4,
    color: "#64748b",
    fontSize: 12,
    fontWeight: "600",
  },
  searchResultMetaDark: {
    color: "#94a3b8",
  },
  searchEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: "#64748b",
    fontSize: 13,
    fontWeight: "600",
  },
  searchEmptyDark: {
    color: "#94a3b8",
  },
  primaryButton: {
    backgroundColor: "#0ea5e9",
  },
  secondaryButton: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  secondaryButtonDark: {
    backgroundColor: "#111827",
    borderColor: "#334155",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 26,
    lineHeight: 26,
    fontWeight: "800",
    marginTop: -2,
  },
  primaryButtonTextLandscape: {
    fontSize: 24,
    lineHeight: 24,
  },
  secondaryButtonText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryButtonTextLandscape: {
    fontSize: 12,
  },
  secondaryButtonTextDark: {
    color: "#f8fafc",
  },
  banner: {
    position: "absolute",
    top: 12,
    left: 12,
    right: 12,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    gap: 12,
  },
  bannerLandscape: {
    left: 8,
    right: "auto",
    top: 8,
    maxWidth: 420,
  },
  bannerText: {
    flex: 1,
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  bannerButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#1d4ed8",
  },
  bannerButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  deleteButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#dc2626",
  },
  deleteButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  edgePanel: {
    position: "absolute",
    left: 12,
    right: 12,
    top: 12,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.98)",
    borderWidth: 1,
    borderColor: "#dbeafe",
    padding: 14,
    gap: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  edgePanelDark: {
    backgroundColor: "rgba(15, 23, 42, 0.98)",
    borderColor: "#334155",
  },
  edgePanelLandscape: {
    maxWidth: 380,
  },
  edgePanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  edgePanelTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  edgePanelTitleDark: {
    color: "#f8fafc",
  },
  edgePanelMeta: {
    marginTop: 4,
    color: "#475569",
    fontSize: 12,
    fontWeight: "600",
  },
  edgePanelMetaDark: {
    color: "#94a3b8",
  },
  edgePanelSection: {
    gap: 8,
  },
  edgePanelLabel: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "700",
  },
  edgePanelLabelDark: {
    color: "#cbd5e1",
  },
  edgePills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  edgePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#f3f4f6",
  },
  edgePillDark: {
    backgroundColor: "#1e293b",
  },
  edgePillActive: {
    backgroundColor: "#0ea5e9",
  },
  edgePillText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  edgePillTextDark: {
    color: "#cbd5e1",
  },
  edgePillTextActive: {
    color: "#ffffff",
  },
  edgeStepper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  edgeStepButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
  },
  edgeStepButtonDark: {
    backgroundColor: "#1e293b",
  },
  edgeStepButtonText: {
    color: "#111827",
    fontSize: 20,
    lineHeight: 20,
    fontWeight: "700",
  },
  edgeStepButtonTextDark: {
    color: "#f8fafc",
  },
  edgeStepValue: {
    minWidth: 18,
    textAlign: "center",
    color: "#111827",
    fontSize: 15,
    fontWeight: "700",
  },
  edgeStepValueDark: {
    color: "#f8fafc",
  },
  edgePalette: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
  },
  edgeSwatch: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "transparent",
  },
  edgeSwatchActive: {
    borderColor: "#0f172a",
  },
  zoomHud: {
    position: "absolute",
    top: 72,
    alignSelf: "center",
    minWidth: 78,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(15, 23, 42, 0.86)",
    alignItems: "center",
    justifyContent: "center",
  },
  zoomHudLandscape: {
    top: 20,
  },
  zoomHudText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  moveToast: {
    position: "absolute",
    top: 84,
    alignSelf: "center",
    maxWidth: 280,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(220, 38, 38, 0.96)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 45,
  },
  moveToastLandscape: {
    top: 24,
  },
  moveToastText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  mapLoadProgress: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
    padding: 12,
    gap: 9,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 8,
    zIndex: 46,
  },
  mapLoadProgressDark: {
    backgroundColor: "rgba(15,23,42,0.96)",
    borderColor: "rgba(255,255,255,0.10)",
  },
  mapLoadProgressLandscape: {
    left: 12,
    right: "auto",
    width: 300,
  },
  mapLoadProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  mapLoadProgressTitle: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  mapLoadProgressTitleDark: {
    color: "#f8fafc",
  },
  mapLoadProgressPercent: {
    color: "#0369a1",
    fontSize: 13,
    fontWeight: "900",
  },
  mapLoadProgressPercentDark: {
    color: "#7dd3fc",
  },
  mapLoadProgressTrack: {
    height: 7,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "rgba(148,163,184,0.24)",
  },
  mapLoadProgressTrackDark: {
    backgroundColor: "rgba(148,163,184,0.22)",
  },
  mapLoadProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#0ea5e9",
  },
  mapLoadOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    backgroundColor: "#f8fafc",
    zIndex: 80,
  },
  mapLoadOverlayDark: {
    backgroundColor: "#020617",
  },
  mapLoadCard: {
    width: "100%",
    maxWidth: 340,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.98)",
    borderWidth: 1,
    borderColor: "rgba(148,163,184,0.28)",
    padding: 14,
    gap: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 8,
  },
  mapLoadCardDark: {
    backgroundColor: "rgba(15,23,42,0.98)",
    borderColor: "rgba(255,255,255,0.10)",
  },
  mapLoadCardLandscape: {
    maxWidth: 300,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
});
